name: note build
# 触发workflow的条件
on:
  push:
    # 只有main分支发生push事件时，才会触发workflow
    branches:
      - main
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE
  pull_request:
    branches: [main]

# jobs表示执行的一项或多项任务
jobs:
  deploy: # 任务的job_id，具体名称自定义，这里build代表打包
    runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    steps:
      # git submodule
      - uses: actions/checkout@v2

      # node
      - name: use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACCESS_TOKEN }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Create target directory
        run: ssh ${{ secrets.USER_NAME }}@${{ secrets.SERVER_HOST }} "mkdir -p ${{ secrets.TARGET_MYTOOLS }}"
        shell: bash

      - name: deploy to server
        uses: AEnterprise/rsync-deploy@v1.0.2
        with:
          switches: -avzr --delete
          path: ./dist/
          remote_path: ${{ secrets.USER_NAME }}@${{ secrets.SERVER_HOST }}:${{ secrets.TARGET_MYTOOLS }}
          remote_key: ~/.ssh/id_rsa
